// SPDX-License-Identifier: MIT
// Copyright (c) 2026 The Atelier Authors

const frameworkNames = {
  'hosted-script': 'Atelier hosted script',
};

export function installSurfaceFields(model, e) {
  const slots = model?.slots ?? [];
  return `<div class="install-intro"><strong>One hosted script</strong><p>Atelier serves the reviewed UI and runtime. Paste one module script into your page; API calls run directly in that browser through the application's existing same-origin session.</p></div><input type="hidden" name="target" value="hosted-script"><label>Application origin<input name="applicationOrigin" type="url" required placeholder="https://app.example.com"><span class="help">The script and manifest are restricted to this exact origin.</span></label><div class="two-fields"><label>Surface placement<select name="mode"><option value="route">New full page</option><option value="inline">Existing-page mount</option><option value="drawer">Existing-page drawer</option></select></label><label>Customer page path<input name="routePath" value="/atelier-workspace" required></label></div><div class="two-fields"><label>Navigation label<input name="navLabel" value="Workspace" required></label><label>Approved slot<select name="slotId">${slots.map((slot) => `<option value="${e(slot.id)}">${e(slot.id)}</option>`).join('')}</select></label></div><label>Release environment<select name="environment"><option>staging</option><option>production</option></select><span class="help">Publish the selected slot to this environment before opening the page.</span></label><div class="privacy-preview"><strong>Browser authority</strong><p>The script can call only reviewed same-origin HTTP operations in the published surface contract. Your API remains responsible for session authentication, tenant isolation, permissions and object authorization. Add a standard csrf-token meta tag or window.AtelierHost.csrfToken() before enabling mutations.</p></div>`;
}

export function installBundleSummary(result, e, icon) {
  const bundle = result.bundle;
  const targetName = bundle.install.target?.label ?? frameworkNames[bundle.install.framework];
  return `<div class="install-ready"><div>${icon('check')}</div><div><span class="setup-label">Hosted embed ready</span><h3>${e(targetName)}</h3><p>Paste the single insertion snippet below. Atelier serves the UI/runtime; the page performs only approved same-origin API calls. The embed is bound to design contract ${e(bundle.install.designFingerprint.slice(0, 10))} and this exact application origin.</p></div></div><h3>Customer-owned insertion point</h3><div class="install-patches">${bundle.patches.map((entry) => `<details open><summary>${e(entry.target)} · ${e(entry.purpose)}</summary><pre>${e(entry.snippet)}</pre></details>`).join('')}</div><div class="privacy-preview"><strong>Verification is factual</strong><p>Studio verifies that the hosted manifest loaded, the mount rendered and the reviewed browser API client initialized. The receipt does not grant API authority; the customer's API session and permission checks remain authoritative.</p></div><div class="dialog-actions"><button class="btn secondary" data-copy-snippet>Copy script</button><button class="btn secondary" data-copy-agent>Copy coding-agent prompt</button><button class="btn" data-download-install>Download receipt bundle</button></div>`;
}

export function codingAgentPrompt(bundle) {
  return `Install the attached Atelier hosted embed at ${bundle.install.routePath}. Apply the single listed insertion snippet to a customer-owned page; do not add a server bridge, API credential or framework package. Atelier serves the versioned UI/runtime. API calls execute in the browser against reviewed same-origin paths using the application's existing authenticated session. Confirm the customer API still enforces tenant, permission and object authorization. For any mutation, expose the existing CSRF value through a csrf-token meta tag or window.AtelierHost.csrfToken() without copying a credential into the Atelier script. Allow ${new URL(bundle.publicVerification.endpoint).origin} in script-src, connect-src and style-src. Run unit and browser tests, open ${bundle.install.routePath}, verify an approved real API response renders, and verify an unapproved operation cannot be called. Do not add a fallback or proxy.`;
}
