CREATE UNIQUE INDEX IF NOT EXISTS artifacts_scope_id ON artifacts(tenant_id,project_id,id);
CREATE UNIQUE INDEX IF NOT EXISTS jobs_scope_id ON jobs(tenant_id,project_id,id);
CREATE TABLE component_versions(tenant_id TEXT NOT NULL,project_id TEXT NOT NULL,id TEXT NOT NULL,name TEXT NOT NULL,artifact_id TEXT NOT NULL,digest TEXT NOT NULL,project_version TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('draft','approved','published','revoked')),evidence_id TEXT,approved_by TEXT,approved_at INTEGER,review_note TEXT,signature_json TEXT,created_by TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(tenant_id,project_id,id),UNIQUE(tenant_id,project_id,digest),FOREIGN KEY(tenant_id,project_id,artifact_id) REFERENCES artifacts(tenant_id,project_id,id),FOREIGN KEY(tenant_id,project_id,evidence_id) REFERENCES artifacts(tenant_id,project_id,id)) STRICT;
CREATE TABLE agent_profiles(tenant_id TEXT NOT NULL,project_id TEXT NOT NULL,artifact_id TEXT NOT NULL,revision INTEGER NOT NULL,updated_by TEXT NOT NULL,updated_at INTEGER NOT NULL,PRIMARY KEY(tenant_id,project_id),FOREIGN KEY(tenant_id,project_id,artifact_id) REFERENCES artifacts(tenant_id,project_id,id)) STRICT;
CREATE TABLE agent_threads(tenant_id TEXT NOT NULL,project_id TEXT NOT NULL,id TEXT NOT NULL,owner_hash TEXT NOT NULL,owner_type TEXT NOT NULL CHECK(owner_type IN('studio','host')),title TEXT NOT NULL,profile_id TEXT NOT NULL,permission_hash TEXT NOT NULL,permissions_json TEXT NOT NULL,context_cipher TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,active_job_id TEXT,archived_at INTEGER,expires_at INTEGER NOT NULL,created_by TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,PRIMARY KEY(tenant_id,project_id,id),FOREIGN KEY(tenant_id,project_id,profile_id) REFERENCES artifacts(tenant_id,project_id,id),FOREIGN KEY(tenant_id,project_id,active_job_id) REFERENCES jobs(tenant_id,project_id,id)) STRICT;
CREATE INDEX agent_threads_owner ON agent_threads(tenant_id,project_id,owner_hash,updated_at DESC);
CREATE TABLE agent_messages(tenant_id TEXT NOT NULL,project_id TEXT NOT NULL,thread_id TEXT NOT NULL,seq INTEGER NOT NULL,id TEXT NOT NULL,role TEXT NOT NULL,content_cipher TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(tenant_id,project_id,thread_id,seq),UNIQUE(tenant_id,project_id,thread_id,id),FOREIGN KEY(tenant_id,project_id,thread_id) REFERENCES agent_threads(tenant_id,project_id,id) ON DELETE CASCADE) STRICT;
CREATE TABLE agent_events(tenant_id TEXT NOT NULL,project_id TEXT NOT NULL,thread_id TEXT NOT NULL,seq INTEGER NOT NULL,type TEXT NOT NULL,payload_json TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(tenant_id,project_id,thread_id,seq),FOREIGN KEY(tenant_id,project_id,thread_id) REFERENCES agent_threads(tenant_id,project_id,id) ON DELETE CASCADE) STRICT;
CREATE TABLE agent_calls(tenant_id TEXT NOT NULL,project_id TEXT NOT NULL,thread_id TEXT NOT NULL,id TEXT NOT NULL,job_id TEXT,capability_id TEXT NOT NULL,input_cipher TEXT NOT NULL,input_hash TEXT NOT NULL,contract_hash TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('pending','leased','succeeded','failed','denied','uncertain')),lease_hash TEXT,lease_until INTEGER,output_cipher TEXT,output_hash TEXT,created_at INTEGER NOT NULL,completed_at INTEGER,PRIMARY KEY(tenant_id,project_id,id),FOREIGN KEY(tenant_id,project_id,thread_id) REFERENCES agent_threads(tenant_id,project_id,id) ON DELETE CASCADE,FOREIGN KEY(tenant_id,project_id,job_id) REFERENCES jobs(tenant_id,project_id,id)) STRICT;
CREATE TABLE agent_artifact_refs(tenant_id TEXT NOT NULL,project_id TEXT NOT NULL,thread_id TEXT NOT NULL,artifact_id TEXT NOT NULL,pinned INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,PRIMARY KEY(tenant_id,project_id,thread_id,artifact_id),FOREIGN KEY(tenant_id,project_id,thread_id) REFERENCES agent_threads(tenant_id,project_id,id) ON DELETE CASCADE,FOREIGN KEY(tenant_id,project_id,artifact_id) REFERENCES artifacts(tenant_id,project_id,id)) STRICT;
CREATE TABLE agent_feedback(tenant_id TEXT NOT NULL,project_id TEXT NOT NULL,thread_id TEXT NOT NULL,message_id TEXT NOT NULL,value INTEGER NOT NULL CHECK(value IN(-1,1)),created_at INTEGER NOT NULL,PRIMARY KEY(tenant_id,project_id,thread_id,message_id),FOREIGN KEY(tenant_id,project_id,thread_id,message_id) REFERENCES agent_messages(tenant_id,project_id,thread_id,id) ON DELETE CASCADE) STRICT;
CREATE TABLE agent_attachments(tenant_id TEXT NOT NULL,project_id TEXT NOT NULL,thread_id TEXT NOT NULL,id TEXT NOT NULL,name TEXT NOT NULL,media_type TEXT NOT NULL,byte_size INTEGER NOT NULL,content_cipher TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(tenant_id,project_id,thread_id,id),FOREIGN KEY(tenant_id,project_id,thread_id) REFERENCES agent_threads(tenant_id,project_id,id) ON DELETE CASCADE) STRICT;
CREATE TABLE preview_grants(credential_hash TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,project_id TEXT NOT NULL,component_id TEXT NOT NULL,owner_id TEXT NOT NULL,mode TEXT NOT NULL,payload_cipher TEXT NOT NULL,expires_at INTEGER NOT NULL,used_at INTEGER,thread_id TEXT,FOREIGN KEY(tenant_id,project_id,component_id) REFERENCES component_versions(tenant_id,project_id,id),FOREIGN KEY(tenant_id,project_id,thread_id) REFERENCES agent_threads(tenant_id,project_id,id) ON DELETE CASCADE) STRICT;

CREATE TABLE component_signing_keys(tenant_id TEXT NOT NULL,project_id TEXT NOT NULL,id TEXT NOT NULL,public_pem TEXT NOT NULL,private_cipher TEXT NOT NULL,created_at INTEGER NOT NULL,retired_at INTEGER,revoked_at INTEGER,PRIMARY KEY(tenant_id,project_id,id)) STRICT;
